name: BetonQuestAddon
version: '${version}'
author: MrJimin
website: https://www.spigotmc.org/resources/betonquestaddon.120813/
description: Extends BetonQuest with additional powerful features.

api-version: "1.21"

main: com.github.mrjimin.betonquestaddon.BetonQuestAddonPlugin
loader: com.github.mrjimin.betonquestaddon.BetonQuestAddonLoader

dependencies:
  server:
    BetonQuest:
      load: BEFORE
      required: true

    ItemsAdder:
      load: BEFORE
      required: false
    Nexo:
      load: BEFORE
      required: false
    CoinsEngine:
      load: BEFORE
      required: false
    CraftEngine:
      load: BEFORE
      required: false
    HeadDatabase:
      load: BEFORE
      required: false
    AdvancedEnchantments:
      load: BEFORE
      required: false
    Lands:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false

permissions:
  betonquestaddon.command:
    default: op
  betonquestaddon.command.reload:
    default: op
  betonquestaddon.command.give:
    default: op
  betonquestaddon.command.inventory:
    default: op