name: BetonQuestAddon
main: com.github.mrjimin.betonquestaddon.BetonQuestAddonPlugin
version: '${version}'
api-version: 1.20
author: MrJimin
depend:
  - BetonQuest
website: https://www.spigotmc.org/resources/betonquestaddon.120813/
description: Extends BetonQuest with additional powerful features.
permissions:
  betonquestaddon.command:
    default: op
  betonquestaddon.command.reload:
    default: op
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.0